<a href="https://colab.research.google.com/github/swarnayu777/Fake-News-Detection-Model-using-TensorFlow-in-Python/blob/main/Fake_News_Detection_Model_using_TensorFlow_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
data = pd.read_csv("news (2).csv")
data.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [7]:
data = pd.read_csv("news (2).csv")
data.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [8]:
data = data.drop(["Unnamed: 0"], axis=1)
data.head(5)

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [10]:
# Encoding
le = preprocessing.LabelEncoder()
le.fit(data['label'])
data['label'] = le.transform(data['label'])

In [12]:
# Variables Setup
embedding_dim = 50
max_length = 54
padding_type = 'post'
trunc_type = 'post'
oov_tok = "<OOV>"
training_size = 3000
test_portion = 0.1

In [13]:
# Tokenization
title = []
text = []
labels = []
for x in range(training_size):
    title.append(data['title'][x])
    text.append(data['text'][x])
    labels.append(data['label'][x])

tokenizer1 = Tokenizer()
tokenizer1.fit_on_texts(title)
word_index1 = tokenizer1.word_index
vocab_size1 = len(word_index1)
sequences1 = tokenizer1.texts_to_sequences(title)
padded1 = pad_sequences(sequences1, padding=padding_type, truncating=trunc_type)

In [14]:
# Splitting Data for Training and Testing
split = int(test_portion * training_size)
training_sequences1 = padded1[split:training_size]
test_sequences1 = padded1[0:split]
test_labels = labels[0:split]
training_labels = labels[split:training_size]

In [15]:
# Reshaping Data for LSTM
training_sequences1 = np.array(training_sequences1)
test_sequences1 = np.array(test_sequences1)

In [16]:
# Generating Word Embedding
!wget https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
!unzip glove.6B.zip

--2026-06-30 19:37:31--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.06MB/s    in 3m 6s

2026-06-30 19:40:38 (4.43 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt
  inflating: glove.6B.100d.txt
  inflating: glove.6B.200d.txt
  inflating: glove.6B.300d.txt

In [17]:
# glove embeddings
embedding_index = {}
with open('glove.6B.50d.txt', 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = coefs

embedding_matrix = np.zeros((vocab_size1 + 1, embedding_dim))

for word, i in word_index1.items():
    if i < vocab_size1:
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [18]:
# Model Architecture
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size1 + 1, embedding_dim, input_length=max_length,
                              weights=[embedding_matrix], trainable=False),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Conv1D(64, 5, activation='relu'),
    tf.keras.layers.MaxPooling1D(pool_size=4),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │       377,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 377,600 (1.44 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 377,600 (1.44 MB)

In [19]:
# Training the Model
history = model.fit(
    training_sequences1,
    np.array(training_labels),
    epochs=50,
    validation_data=(test_sequences1, np.array(test_labels)),
    verbose=2
)

Epoch 1/50
85/85 - 3s - 37ms/step - accuracy: 0.6174 - loss: 0.6483 - val_accuracy: 0.6900 - val_loss: 0.5723
Epoch 2/50
85/85 - 1s - 10ms/step - accuracy: 0.6981 - loss: 0.5653 - val_accuracy: 0.7167 - val_loss: 0.5212
Epoch 3/50
85/85 - 1s - 15ms/step - accuracy: 0.7400 - loss: 0.5328 - val_accuracy: 0.7400 - val_loss: 0.5072
Epoch 4/50
85/85 - 1s - 9ms/step - accuracy: 0.7733 - loss: 0.4751 - val_accuracy: 0.7667 - val_loss: 0.4876
Epoch 5/50
85/85 - 1s - 15ms/step - accuracy: 0.8022 - loss: 0.4250 - val_accuracy: 0.7633 - val_loss: 0.5037
Epoch 6/50
85/85 - 1s - 10ms/step - accuracy: 0.8370 - loss: 0.3657 - val_accuracy: 0.7667 - val_loss: 0.4991
Epoch 7/50
85/85 - 1s - 15ms/step - accuracy: 0.8485 - loss: 0.3486 - val_accuracy: 0.7433 - val_loss: 0.5362
Epoch 8/50
85/85 - 1s - 11ms/step - accuracy: 0.8500 - loss: 0.3489 - val_accuracy: 0.7733 - val_loss: 0.5224
Epoch 9/50
85/85 - 1s - 15ms/step - accuracy: 0.8881 - loss: 0.2731 - val_accuracy: 0.7567 - val_loss: 0.5258
Epoch 10/50
85/85 - 2s - 24ms/step - accuracy: 0.8952 - loss: 0.2599 - val_accuracy: 0.7733 - val_loss: 0.5879
Epoch 11/50
85/85 - 1s - 15ms/step - accuracy: 0.8893 - loss: 0.2423 - val_accuracy: 0.7600 - val_loss: 0.5921
Epoch 12/50
85/85 - 1s - 15ms/step - accuracy: 0.9119 - loss: 0.2208 - val_accuracy: 0.7667 - val_loss: 0.6025
Epoch 13/50
85/85 - 1s - 15ms/step - accuracy: 0.9200 - loss: 0.2011 - val_accuracy: 0.7833 - val_loss: 0.6508
Epoch 14/50
85/85 - 1s - 9ms/step - accuracy: 0.9248 - loss: 0.1884 - val_accuracy: 0.7333 - val_loss: 0.6525
Epoch 15/50
85/85 - 1s - 9ms/step - accuracy: 0.9244 - loss: 0.1815 - val_accuracy: 0.7100 - val_loss: 0.7996
Epoch 16/50
85/85 - 1s - 10ms/step - accuracy: 0.9170 - loss: 0.1943 - val_accuracy: 0.7433 - val_loss: 0.7200
Epoch 17/50
85/85 - 1s - 9ms/step - accuracy: 0.9326 - loss: 0.1710 - val_accuracy: 0.7600 - val_loss: 0.5941
Epoch 18/50
85/85 - 1s - 9ms/step - accuracy: 0.9404 - loss: 0.1531 - val_accuracy: 0.7367 - val_loss: 0.7566
Epoch 19/50
85/85 - 1s - 9ms/step - accuracy: 0.9381 - loss: 0.1579 - val_accuracy: 0.7300 - val_loss: 0.7191
Epoch 20/50
85/85 - 1s - 13ms/step - accuracy: 0.9544 - loss: 0.1244 - val_accuracy: 0.7267 - val_loss: 0.8239
Epoch 21/50
85/85 - 2s - 18ms/step - accuracy: 0.9433 - loss: 0.1461 - val_accuracy: 0.7500 - val_loss: 0.6855
Epoch 22/50
85/85 - 1s - 10ms/step - accuracy: 0.9530 - loss: 0.1234 - val_accuracy: 0.7467 - val_loss: 0.8708
Epoch 23/50
85/85 - 1s - 14ms/step - accuracy: 0.9548 - loss: 0.1242 - val_accuracy: 0.7400 - val_loss: 0.8569
Epoch 24/50
85/85 - 1s - 10ms/step - accuracy: 0.9622 - loss: 0.1019 - val_accuracy: 0.7267 - val_loss: 0.9758
Epoch 25/50
85/85 - 1s - 10ms/step - accuracy: 0.9652 - loss: 0.1022 - val_accuracy: 0.7533 - val_loss: 0.7859
Epoch 26/50
85/85 - 1s - 9ms/step - accuracy: 0.9585 - loss: 0.1103 - val_accuracy: 0.7433 - val_loss: 0.7539
Epoch 27/50
85/85 - 1s - 15ms/step - accuracy: 0.9615 - loss: 0.1055 - val_accuracy: 0.7200 - val_loss: 0.8110
Epoch 28/50
85/85 - 1s - 9ms/step - accuracy: 0.9593 - loss: 0.1058 - val_accuracy: 0.7300 - val_loss: 0.8089
Epoch 29/50
85/85 - 1s - 15ms/step - accuracy: 0.9674 - loss: 0.0934 - val_accuracy: 0.7367 - val_loss: 0.8967
Epoch 30/50
85/85 - 1s - 9ms/step - accuracy: 0.9667 - loss: 0.0881 - val_accuracy: 0.7200 - val_loss: 1.0013
Epoch 31/50
85/85 - 1s - 9ms/step - accuracy: 0.9626 - loss: 0.1042 - val_accuracy: 0.7567 - val_loss: 0.9401
Epoch 32/50
85/85 - 1s - 10ms/step - accuracy: 0.9707 - loss: 0.0793 - val_accuracy: 0.7433 - val_loss: 0.8907
Epoch 33/50
85/85 - 1s - 16ms/step - accuracy: 0.9644 - loss: 0.0928 - val_accuracy: 0.7600 - val_loss: 0.8663
Epoch 34/50
85/85 - 1s - 15ms/step - accuracy: 0.9689 - loss: 0.0880 - val_accuracy: 0.7267 - val_loss: 0.9214
Epoch 35/50
85/85 - 1s - 9ms/step - accuracy: 0.9719 - loss: 0.0747 - val_accuracy: 0.7700 - val_loss: 0.8954
Epoch 36/50
85/85 - 1s - 15ms/step - accuracy: 0.9696 - loss: 0.0815 - val_accuracy: 0.7400 - val_loss: 0.9799
Epoch 37/50
85/85 - 1s - 10ms/step - accuracy: 0.9781 - loss: 0.0686 - val_accuracy: 0.7500 - val_loss: 0.8660
Epoch 38/50
85/85 - 1s - 14ms/step - accuracy: 0.9733 - loss: 0.0707 - val_accuracy: 0.7700 - val_loss: 0.7984
Epoch 39/50
85/85 - 1s - 9ms/step - accuracy: 0.9648 - loss: 0.0935 - val_accuracy: 0.7567 - val_loss: 0.8232
Epoch 40/50
85/85 - 1s - 10ms/step - accuracy: 0.9730 - loss: 0.0733 - val_accuracy: 0.7300 - val_loss: 0.9488
Epoch 41/50
85/85 - 1s - 14ms/step - accuracy: 0.9730 - loss: 0.0740 - val_accuracy: 0.7300 - val_loss: 0.8116
Epoch 42/50
85/85 - 1s - 15ms/step - accuracy: 0.9748 - loss: 0.0689 - val_accuracy: 0.7333 - val_loss: 0.8535
Epoch 43/50
85/85 - 1s - 15ms/step - accuracy: 0.9763 - loss: 0.0642 - val_accuracy: 0.7700 - val_loss: 0.9450
Epoch 44/50
85/85 - 1s - 12ms/step - accuracy: 0.9689 - loss: 0.0892 - val_accuracy: 0.7333 - val_loss: 0.8374
Epoch 45/50
85/85 - 2s - 19ms/step - accuracy: 0.9770 - loss: 0.0563 - val_accuracy: 0.7600 - val_loss: 1.0045
Epoch 46/50
85/85 - 2s - 23ms/step - accuracy: 0.9707 - loss: 0.0755 - val_accuracy: 0.7467 - val_loss: 0.8795
Epoch 47/50
85/85 - 1s - 10ms/step - accuracy: 0.9841 - loss: 0.0420 - val_accuracy: 0.7100 - val_loss: 1.0719
Epoch 48/50
85/85 - 1s - 9ms/step - accuracy: 0.9730 - loss: 0.0738 - val_accuracy: 0.7400 - val_loss: 0.8718
Epoch 49/50
85/85 - 1s - 10ms/step - accuracy: 0.9756 - loss: 0.0683 - val_accuracy: 0.7333 - val_loss: 0.9438
Epoch 50/50
85/85 - 1s - 15ms/step - accuracy: 0.9737 - loss: 0.0706 - val_accuracy: 0.7233 - val_loss: 0.9877

In [28]:
 X = ""

sequences = tokenizer1.texts_to_sequences([X])
sequences = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
if model.predict(sequences, verbose=0)[0][0] >= 0.5:
    print("This news is True")
else:
    print("This news is False")

This news is True